# Set update schedule for GitHub Actions

version: 2
updates:
  # Maintain dependencies for actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Maintain dependencies for web docs/npm
  - package-ecosystem: 'npm'
    directory: '/web'
    schedule:
      interval: 'weekly'
    groups:
      web-deps:
        patterns:
          # Group all the web deps together to keep the PR spam down
          - '*'
