# Set update schedule for GitHub Actions

version: 2
updates:
  # Maintain dependencies for actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      actions:
        patterns:
          - '*'
