changelog:
  categories:
    - title: 🏕 Features
      labels:
        - feature
    - title: 🧪 Improvements
      labels:
        - enhancement
    - title: 🐞 Bug fixes
      labels:
        - bug
        - regression
    - title: 🎛️ Miscellaneous
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - bug
          - regression
          - feature
          - enhancement
    - title: 👒 Dependencies
      labels:
        - dependencies
