changelog:
  categories:
    - title: 🏕 Features
      labels:
        - feature
    - title: 🐞 Bug fixes
      labels:
        - bug
    - title: 🎛️ Miscellaneous
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - bug
          - feature
    - title: 👒 Dependencies
      labels:
        - dependencies
