#!/bin/sh
# $Id$

AUTOCONF=${AUTOCONF:-autoconf}
AUTOMAKE=${AUTOMAKE:-automake}
ACLOCAL=${ACLOCAL:-aclocal}
AUTOHEADER=${AUTOHEADER:-autoheader}
LIBTOOLIZE=${LIBTOOLIZE:-libtoolize}

$ACLOCAL
$LIBTOOLIZE --force
$AUTOHEADER
$AUTOMAKE -a
$AUTOCONF
