ARG IMAGE=registry.gitlab.com/brndnmtthws-oss/conky
FROM ${IMAGE}/builder/ubuntu-base:latest

RUN wget -q https://apt.llvm.org/llvm-snapshot.gpg.key \
  && apt-key add llvm-snapshot.gpg.key \
  && add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main' \
  && DEBIAN_FRONTEND=noninteractive \
  apt-get install -qy --no-install-recommends \
  clang-11 \
  lldb-11 \
  lld-11 \
  libc++-11-dev \
  libc++abi-11-dev \
  clang-tools-11 \
  clang-format-11 \
  clang-tidy-11 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
