ARG IMAGE=registry.gitlab.com/brndnmtthws-oss/conky
FROM ${IMAGE}/builder/ubuntu-base:latest

RUN wget -q https://apt.llvm.org/llvm-snapshot.gpg.key \
  && apt-key add llvm-snapshot.gpg.key \
  && add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-7 main' \
  && DEBIAN_FRONTEND=noninteractive \
  apt-get install -qy --no-install-recommends \
  clang-7 \
  lldb-7 \
  lld-7 \
  libc++-7-dev \
  libc++abi-7-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && wget https://deb.nodesource.com/setup_11.x -O npm.sh \
  && bash npm.sh \
  && rm npm.sh \
  && apt-get install -y nodejs \
  && npm install -g lcov-summary \
  && npm cache clean --force
