# set(RELEASE true)

set(VERSION_MAJOR "1")
set(VERSION_MINOR "25")
set(VERSION_PATCH "0")

execute_process(COMMAND ${APP_UNAME} -sm
  RESULT_VARIABLE RETVAL
  OUTPUT_VARIABLE BUILD_ARCH
  OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(COMMAND ${APP_GIT} rev-parse --short HEAD
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  RESULT_VARIABLE RETVAL
  OUTPUT_VARIABLE GIT_SHORT_SHA
  OUTPUT_STRIP_TRAILING_WHITESPACE)
  
set(RELEASE_VERSION "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}")

if(RELEASE)
  set(VERSION ${RELEASE_VERSION})
else(RELEASE)
  set(VERSION
    "${RELEASE_VERSION}-pre-${GIT_SHORT_SHA}")
endif(RELEASE)

set(COPYRIGHT "Copyright Brenden Matthews, et al, 2005-2026")
