name: 'Pull Request Labeler'
on:
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run labeler
        uses: actions/labeler@v5
        with:
          sync-labels: true
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
