[build]
command = "bun run build"
publish = "out"

[build.environment]
BUN_VERSION = "1.3.10"

# Include the doc dir in the build ignore command
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../doc/"
